CREATE TABLE "ab_events" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ab_events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"event_type" text NOT NULL,
	"variant" text NOT NULL,
	"lang" text NOT NULL,
	"src" text DEFAULT 'direct',
	"plan" text,
	"session_id" text,
	"ip" text,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "comics" (
	"cv_id" text PRIMARY KEY NOT NULL,
	"volume_name" text NOT NULL,
	"volume_cv_id" text,
	"issue_number" text NOT NULL,
	"name" text,
	"publisher" text,
	"cover_date" text,
	"cover_image_url" text,
	"description" text,
	"is_key_issue" boolean DEFAULT false NOT NULL,
	"key_issue_reason" text,
	"characters" jsonb DEFAULT '[]'::jsonb,
	"story_arcs" jsonb DEFAULT '[]'::jsonb,
	"cv_url" text,
	"sources" jsonb DEFAULT '[]'::jsonb,
	"last_synced_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "commodities" (
	"symbol" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"price_per_oz_eur_cents" integer,
	"price_per_oz_usd_cents" integer,
	"price_updated_at" timestamp,
	"yahoo_ticker" text,
	"unit" text DEFAULT 'troy_oz' NOT NULL,
	"last_synced_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "cs2_items" (
	"market_hash_name" text PRIMARY KEY NOT NULL,
	"weapon_type" text,
	"skin_name" text,
	"exterior" text,
	"rarity" text,
	"is_stat_trak" boolean DEFAULT false NOT NULL,
	"is_souvenir" boolean DEFAULT false NOT NULL,
	"icon_url" text,
	"suggested_price_cents" integer,
	"min_price_cents" integer,
	"price_updated_at" timestamp,
	"last_synced_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "ebay_cache" (
	"query" text PRIMARY KEY NOT NULL,
	"data" jsonb NOT NULL,
	"expires_at" timestamp NOT NULL,
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "games_tech" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"platform" text NOT NULL,
	"category" text DEFAULT 'game' NOT NULL,
	"loose_price_cents" integer,
	"cib_price_cents" integer,
	"new_price_cents" integer,
	"price_updated_at" text,
	"release_year" integer,
	"image_url" text,
	"pricecharting_url" text,
	"cex_box_id" text,
	"cex_sell_price_cents" integer,
	"cex_cash_price_cents" integer,
	"igdb_id" integer,
	"description" text,
	"genres" jsonb DEFAULT '[]'::jsonb,
	"cover_url" text,
	"sources" jsonb DEFAULT '[]'::jsonb,
	"last_synced_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "lego_sets" (
	"set_number" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"theme" text DEFAULT '' NOT NULL,
	"theme_id" integer,
	"year" integer,
	"pieces" integer,
	"image_url" text,
	"brickowl_id" text,
	"brickowl_url" text,
	"market_price_gbp" real,
	"market_price_updated_at" timestamp,
	"launch_date" text,
	"exit_date" text,
	"msrp_usd" real,
	"msrp_gbp" real,
	"msrp_eur" real,
	"rebrickable_url" text,
	"brickset_url" text DEFAULT '' NOT NULL,
	"sources" jsonb DEFAULT '[]'::jsonb,
	"last_synced_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "mtg_cards" (
	"id" text PRIMARY KEY NOT NULL,
	"oracle_id" text,
	"name" text NOT NULL,
	"set_code" text NOT NULL,
	"set_name" text,
	"collector_number" text,
	"rarity" text,
	"released_at" text,
	"mana_cost" text,
	"type_line" text,
	"oracle_text" text,
	"edhrec_rank" integer,
	"image_small_url" text,
	"image_large_url" text,
	"image_png_url" text,
	"price_eur_cents" integer,
	"price_eur_foil_cents" integer,
	"price_usd_cents" integer,
	"price_usd_foil_cents" integer,
	"price_updated_at" timestamp,
	"tcgplayer_url" text,
	"cardmarket_url" text,
	"last_synced_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "pokemon_cards" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"local_id" text NOT NULL,
	"set_id" text,
	"set_name" text,
	"serie_name" text,
	"release_date" text,
	"rarity" text,
	"hp" integer,
	"types" jsonb DEFAULT '[]'::jsonb,
	"image_small_url" text,
	"image_large_url" text,
	"price_eur_cents" integer,
	"price_usd_cents" integer,
	"price_updated_at" timestamp,
	"lang" text DEFAULT 'en' NOT NULL,
	"last_synced_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "portfolio_snapshots" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "portfolio_snapshots_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"date" text NOT NULL,
	"value_cents" integer NOT NULL,
	"cost_cents" integer NOT NULL,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "preregistrations" (
	"id" text PRIMARY KEY NOT NULL,
	"email" text NOT NULL,
	"plan" text DEFAULT 'free' NOT NULL,
	"paid" boolean DEFAULT false,
	"stripe_session_id" text,
	"registered_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "sports_cards" (
	"id" text PRIMARY KEY NOT NULL,
	"sport" text NOT NULL,
	"name" text NOT NULL,
	"full_name" text,
	"set_name" text,
	"year" integer,
	"player_name" text,
	"card_number" text,
	"loose_price_cents" integer,
	"graded_price_cents" integer,
	"image_url" text,
	"pricecharting_url" text,
	"price_updated_at" timestamp,
	"last_synced_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" text PRIMARY KEY NOT NULL,
	"email" text NOT NULL,
	"name" text DEFAULT '' NOT NULL,
	"password_hash" text NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"email_verified" boolean DEFAULT false,
	"verify_token" text,
	"plan" text DEFAULT 'free',
	"stripe_customer_id" text,
	"reset_token" text,
	"reset_token_expiry" timestamp,
	"google_id" text
);
--> statement-breakpoint
CREATE INDEX "ab_events_variant_idx" ON "ab_events" USING btree ("variant");--> statement-breakpoint
CREATE INDEX "ab_events_type_idx" ON "ab_events" USING btree ("event_type");--> statement-breakpoint
CREATE INDEX "comics_volume_name_idx" ON "comics" USING btree ("volume_name");--> statement-breakpoint
CREATE INDEX "comics_publisher_idx" ON "comics" USING btree ("publisher");--> statement-breakpoint
CREATE INDEX "comics_key_issue_idx" ON "comics" USING btree ("is_key_issue");--> statement-breakpoint
CREATE INDEX "comics_cover_date_idx" ON "comics" USING btree ("cover_date");--> statement-breakpoint
CREATE INDEX "cs2_items_weapon_idx" ON "cs2_items" USING btree ("weapon_type");--> statement-breakpoint
CREATE INDEX "cs2_items_rarity_idx" ON "cs2_items" USING btree ("rarity");--> statement-breakpoint
CREATE INDEX "cs2_items_exterior_idx" ON "cs2_items" USING btree ("exterior");--> statement-breakpoint
CREATE INDEX "cs2_items_name_idx" ON "cs2_items" USING btree ("skin_name");--> statement-breakpoint
CREATE INDEX "games_tech_platform_idx" ON "games_tech" USING btree ("platform");--> statement-breakpoint
CREATE INDEX "games_tech_category_idx" ON "games_tech" USING btree ("category");--> statement-breakpoint
CREATE INDEX "games_tech_name_idx" ON "games_tech" USING btree ("name");--> statement-breakpoint
CREATE INDEX "lego_sets_theme_idx" ON "lego_sets" USING btree ("theme");--> statement-breakpoint
CREATE INDEX "lego_sets_year_idx" ON "lego_sets" USING btree ("year");--> statement-breakpoint
CREATE INDEX "lego_sets_exit_idx" ON "lego_sets" USING btree ("exit_date");--> statement-breakpoint
CREATE INDEX "mtg_cards_name_idx" ON "mtg_cards" USING btree ("name");--> statement-breakpoint
CREATE INDEX "mtg_cards_oracle_id_idx" ON "mtg_cards" USING btree ("oracle_id");--> statement-breakpoint
CREATE INDEX "mtg_cards_set_idx" ON "mtg_cards" USING btree ("set_code");--> statement-breakpoint
CREATE INDEX "mtg_cards_rarity_idx" ON "mtg_cards" USING btree ("rarity");--> statement-breakpoint
CREATE INDEX "pokemon_cards_name_idx" ON "pokemon_cards" USING btree ("name");--> statement-breakpoint
CREATE INDEX "pokemon_cards_set_idx" ON "pokemon_cards" USING btree ("set_id");--> statement-breakpoint
CREATE INDEX "pokemon_cards_rarity_idx" ON "pokemon_cards" USING btree ("rarity");--> statement-breakpoint
CREATE UNIQUE INDEX "snapshots_user_date_idx" ON "portfolio_snapshots" USING btree ("user_id","date");--> statement-breakpoint
CREATE UNIQUE INDEX "preregs_email_idx" ON "preregistrations" USING btree ("email");--> statement-breakpoint
CREATE INDEX "sports_cards_sport_idx" ON "sports_cards" USING btree ("sport");--> statement-breakpoint
CREATE INDEX "sports_cards_name_idx" ON "sports_cards" USING btree ("name");--> statement-breakpoint
CREATE INDEX "sports_cards_player_idx" ON "sports_cards" USING btree ("player_name");--> statement-breakpoint
CREATE INDEX "sports_cards_sport_name_idx" ON "sports_cards" USING btree ("sport","name");--> statement-breakpoint
CREATE UNIQUE INDEX "users_email_idx" ON "users" USING btree ("email");--> statement-breakpoint
CREATE INDEX "users_google_id_idx" ON "users" USING btree ("google_id");